### ISSUE TITLE
How can we improve ATF documentation?

### ISSUE THREAD

**Issue by gstaas** [SonyWWS/ATF#26]
@gstaas @vkashkash @ColinCren @silvesthu @RomainBL @JelleVM @pdrasko @vorptronica @fuleshu @mstum @RoyAwesome @lordmortis @StirfireStudios

Because of your interest in ATF, we want your feedback to help us improve ATF documentation.

The fundamental question is: What would help you learn and use ATF?
In reflecting on this, you might want to consider:
* What would help you get started using ATF? 
*  What topics would you like to see covered in the documentation that aren't currently? 
*  What parts of the documentation need the most improvement? 
* How can we improve documentation organization? 
* Do you like the formatting of document pages? Any suggestions? More graphics and screen shots? Color usage? 
* Access: Do you like online documents? A wiki? Would you prefer downloaded documentation? In what formats: PDF, ePub, mobi, others? 
* What other items would you find useful: More test code? Tutorials, what topics?
        Reference cards, that is, a few pages containing key information?
        FAQ?
        More videos, what topics?
        Examples, what areas?
        More samples, what areas?

Please send responses to gary_staas@playstation.sony.com by Friday, October 3, 2014. Or just leave your comments on this issue. Thanks!

**Comment by kiwidoggie** [comment]
I've been trying to figure out https://github.com/SonyWWS/ATF/wiki/Value-Editors-and-Value-Editing-Controls for the longest time. I am using WPF and it seems that the WPF counterparts of ATF don't have any clear documentation with the variations from the WinForms counterparts. I'm not sure if I'm just missing it, but I've been doing much trial and error with ATF in WPF.

**Comment by abeckus** [comment]
The WPF/ATF  lacks features, docs, robustness, it is more of a work in progress than full feature framework.
WinForm/ATF is under development for many years so it is more robust and feature complete than WPF counter part.
Unfortunately, at this point there is no plan to improve WPF/ATF.
Winform/ATF offers direct2d, skinning and lots of control and editors.

note: using ATF without DOM would be harder since large part of ATF implemented using DOM.
Alan.
