### ISSUE TITLE
PropertyGrid does not update when using keyboard to select ListView item

### ISSUE THREAD

**Issue by nrvllrgrs** [SonyWWS/ATF#50]
In SimpleDomEditor, if you add multiple Events to the XML and use the keyboard to change your selection, the property grid does not reflect that change. What is the ideal way to update the property grid? I'm building a tool based on this sample.

**Comment by abeckus** [comment]
Thanks for reporting the bug.
It seems that the bug is in the class ListViewAdapter located at:  ..\Framework\Atf.Gui.WinForms\Applications\Listers
Look at the constructor istViewAdapter(ListView listView)
listView.SelectedIndexChanged  is not wired.
The above event should be wired and properly handled.
I will make a fix with next ATF update.
meanwhile you can fix it locally until next ATF update.

Alan

**Comment by abeckus** [comment]
fixed,
Thanks for reporting the bug.

Alan
